name: nicolo-thesis
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - git+https://github.com/nicologhielmetti/hls4ml.git@profiling-recurrent#egg=hls4ml[profiling]
    - matplotlib
    - numpy
    - scikit-learn
    - tensorflow=2.7.0
    - git+https://github.com/nicologhielmetti/qkeras.git@flopo-quantization